export const LIST_PRODUCT_REQUEST = 'LIST_PRODUCT_REQUEST';
export const LIST_PRODUCT_SUCCESS = 'LIST_PRODUCT_SUCCESS';
export const LIST_PRODUCT_FAILED = 'LIST_PRODUCT_FAILED';

export const LIST_PRODUCT_DETAIL_REQUEST = 'LIST_PRODUCT_DETAIL_REQUEST';
export const LIST_PRODUCT_DETAIL_SUCCESS = 'LIST_PRODUCT_DETAIL_SUCCESS';
export const LIST_PRODUCT_DETAIL_FAILED = 'LIST_PRODUCT_DETAIL_FAILED';

export const LIST_MYORDERS_REQUEST = 'LIST_MYORDERS_REQUEST';
export const LIST_MYORDERS_SUCCESS = 'LIST_MYORDERS_SUCCESS';
export const LIST_MYORDERS_FAILED = 'LIST_MYORDERS_FAILED';

export const CANCELLED_ORDERS = 'CANCELLED_ORDERS';
export const CANCELLED_ORDERS_FAILED = 'CANCELLED_ORDERS_FAILED';

export const MODAL_VERIFY_CODE_VISIBLE = 'MODAL_VERIFY_CODE_VISIBLE';
export const VERIFY_ORDER = 'VERIFY_ORDER';
export const CREATE_ORDER = 'CREATE_ORDER';
